version: 2

models:
  - name: silver_vw_customers
    description: "Cleaned customer records (from bronze_customers)."
    columns:
      - name: customer_id
        tests: [not_null, unique]
      - name: email
        description: "Lowercased customer email."
      - name: loyalty_status
        description: "Normalized to lowercase."

  - name: silver_vw_products
    description: "Cleaned product records (from bronze_products)."
    columns:
      - name: product_id
        tests: [not_null, unique]
      - name: unit_price
        tests: [not_null]

  - name: silver_vw_orders
    description: "Order headers with normalized status."
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]
      - name: order_date
        tests: [not_null]

  - name: silver_vw_order_items
    description: "Order line items with computed line_amount."
    columns:
      - name: order_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: line_amount
        tests: [not_null]
